/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LogicalAnd */

#ifndef _Included_LogicalAnd
#define _Included_LogicalAnd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LogicalAnd
 * Method:    logAnd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_LogicalAnd_logAnd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
